# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MiQk5JBErjoQMmYwmejxn8O76MnkYtgO
"""

#program to make calculator

import math
print("\t____calculator____")

def sum(a,b):
  a += b
  return a

def sub(a,b):
  if a>b:
   a -= b
   return a

  else:
    b -= a
    return b

def mul(a,b):
  a*=b
  return a

def div(a,b):
  q=a/b
  r=a%b
  print("the quotient is ",q)
  print("the remainder is ",r)

def sqr(a):
  x = math.sqrt(a)
  return x

while True:
 print("\n\n choose the operation you want to perform : ")
 print("\n\t1.Addition")
 print("\n\t2.subtraction")
 print("\n\t3.multiplication")
 print("\n\t4.division")
 print("\n\t5.square root")
 print("\n\t6.exit")

 choice = int(input('>'))

 if choice==1:
  print("\n\nenter the two no : ")
  num1=int(input(">"))
  num2=int(input(">"))
  s=sum(num1,num2)
  print(s)


 elif choice==2:
  print("\n\nenter the two no : ")
  num1=int(input(">"))
  num2=int(input(">"))
  s=sub(num1,num2)
  print(s)

 elif choice==3:
  print("\n\nenter the two no : ")
  num1=int(input(">"))
  num2=int(input(">"))
  s=mul(num1,num2)
  print(s)


 elif choice==4:
  print("\n\nenter the two no : ")
  num1=int(input(">"))
  num2=int(input(">"))
  s=div(num1,num2)
  print(s)

 elif choice==5:
  print("\n\nenter the no : ")
  num1=int(input(">"))
  r=sqr(num1)
  print(r)

 else:
  print("\n you choose to exit")
  break